export type Country = { name: string; iso: string; dial: string };

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", iso: "AF", dial: "+93" },
  { name: "Afrique du Sud", iso: "ZA", dial: "+27" },
  { name: "Albanie", iso: "AL", dial: "+355" },
  { name: "Algérie", iso: "DZ", dial: "+213" },
  { name: "Allemagne", iso: "DE", dial: "+49" },
  { name: "Andorre", iso: "AD", dial: "+376" },
  { name: "Angola", iso: "AO", dial: "+244" },
  { name: "Arabie saoudite", iso: "SA", dial: "+966" },
  { name: "Argentine", iso: "AR", dial: "+54" },
  { name: "Arménie", iso: "AM", dial: "+374" },
  { name: "Australie", iso: "AU", dial: "+61" },
  { name: "Autriche", iso: "AT", dial: "+43" },
  { name: "Azerbaïdjan", iso: "AZ", dial: "+994" },
  { name: "Bahamas", iso: "BS", dial: "+1242" },
  { name: "Bahreïn", iso: "BH", dial: "+973" },
  { name: "Bangladesh", iso: "BD", dial: "+880" },
  { name: "Belgique", iso: "BE", dial: "+32" },
  { name: "Bénin", iso: "BJ", dial: "+229" },
  { name: "Bhoutan", iso: "BT", dial: "+975" },
  { name: "Biélorussie", iso: "BY", dial: "+375" },
  { name: "Birmanie", iso: "MM", dial: "+95" },
  { name: "Bolivie", iso: "BO", dial: "+591" },
  { name: "Bosnie-Herzégovine", iso: "BA", dial: "+387" },
  { name: "Botswana", iso: "BW", dial: "+267" },
  { name: "Brésil", iso: "BR", dial: "+55" },
  { name: "Brunei", iso: "BN", dial: "+673" },
  { name: "Bulgarie", iso: "BG", dial: "+359" },
  { name: "Burkina Faso", iso: "BF", dial: "+226" },
  { name: "Burundi", iso: "BI", dial: "+257" },
  { name: "Cambodge", iso: "KH", dial: "+855" },
  { name: "Cameroun", iso: "CM", dial: "+237" },
  { name: "Canada", iso: "CA", dial: "+1" },
  { name: "Cap-Vert", iso: "CV", dial: "+238" },
  { name: "Chili", iso: "CL", dial: "+56" },
  { name: "Chine", iso: "CN", dial: "+86" },
  { name: "Chypre", iso: "CY", dial: "+357" },
  { name: "Colombie", iso: "CO", dial: "+57" },
  { name: "Comores", iso: "KM", dial: "+269" },
  { name: "Congo", iso: "CG", dial: "+242" },
  { name: "Congo (RDC)", iso: "CD", dial: "+243" },
  { name: "Corée du Nord", iso: "KP", dial: "+850" },
  { name: "Corée du Sud", iso: "KR", dial: "+82" },
  { name: "Costa Rica", iso: "CR", dial: "+506" },
  { name: "Côte d'Ivoire", iso: "CI", dial: "+225" },
  { name: "Croatie", iso: "HR", dial: "+385" },
  { name: "Cuba", iso: "CU", dial: "+53" },
  { name: "Danemark", iso: "DK", dial: "+45" },
  { name: "Djibouti", iso: "DJ", dial: "+253" },
  { name: "Dominique", iso: "DM", dial: "+1767" },
  { name: "Égypte", iso: "EG", dial: "+20" },
  { name: "Émirats arabes unis", iso: "AE", dial: "+971" },
  { name: "Équateur", iso: "EC", dial: "+593" },
  { name: "Érythrée", iso: "ER", dial: "+291" },
  { name: "Espagne", iso: "ES", dial: "+34" },
  { name: "Estonie", iso: "EE", dial: "+372" },
  { name: "Eswatini", iso: "SZ", dial: "+268" },
  { name: "États-Unis", iso: "US", dial: "+1" },
  { name: "Éthiopie", iso: "ET", dial: "+251" },
  { name: "Fidji", iso: "FJ", dial: "+679" },
  { name: "Finlande", iso: "FI", dial: "+358" },
  { name: "France", iso: "FR", dial: "+33" },
  { name: "Gabon", iso: "GA", dial: "+241" },
  { name: "Gambie", iso: "GM", dial: "+220" },
  { name: "Géorgie", iso: "GE", dial: "+995" },
  { name: "Ghana", iso: "GH", dial: "+233" },
  { name: "Grèce", iso: "GR", dial: "+30" },
  { name: "Guatemala", iso: "GT", dial: "+502" },
  { name: "Guinée", iso: "GN", dial: "+224" },
  { name: "Guinée-Bissau", iso: "GW", dial: "+245" },
  { name: "Guinée équatoriale", iso: "GQ", dial: "+240" },
  { name: "Guyana", iso: "GY", dial: "+592" },
  { name: "Haïti", iso: "HT", dial: "+509" },
  { name: "Honduras", iso: "HN", dial: "+504" },
  { name: "Hongrie", iso: "HU", dial: "+36" },
  { name: "Inde", iso: "IN", dial: "+91" },
  { name: "Indonésie", iso: "ID", dial: "+62" },
  { name: "Irak", iso: "IQ", dial: "+964" },
  { name: "Iran", iso: "IR", dial: "+98" },
  { name: "Irlande", iso: "IE", dial: "+353" },
  { name: "Islande", iso: "IS", dial: "+354" },
  { name: "Israël", iso: "IL", dial: "+972" },
  { name: "Italie", iso: "IT", dial: "+39" },
  { name: "Jamaïque", iso: "JM", dial: "+1876" },
  { name: "Japon", iso: "JP", dial: "+81" },
  { name: "Jordanie", iso: "JO", dial: "+962" },
  { name: "Kazakhstan", iso: "KZ", dial: "+7" },
  { name: "Kenya", iso: "KE", dial: "+254" },
  { name: "Kirghizistan", iso: "KG", dial: "+996" },
  { name: "Koweït", iso: "KW", dial: "+965" },
  { name: "Laos", iso: "LA", dial: "+856" },
  { name: "Lesotho", iso: "LS", dial: "+266" },
  { name: "Lettonie", iso: "LV", dial: "+371" },
  { name: "Liban", iso: "LB", dial: "+961" },
  { name: "Liberia", iso: "LR", dial: "+231" },
  { name: "Libye", iso: "LY", dial: "+218" },
  { name: "Liechtenstein", iso: "LI", dial: "+423" },
  { name: "Lituanie", iso: "LT", dial: "+370" },
  { name: "Luxembourg", iso: "LU", dial: "+352" },
  { name: "Macédoine du Nord", iso: "MK", dial: "+389" },
  { name: "Madagascar", iso: "MG", dial: "+261" },
  { name: "Malaisie", iso: "MY", dial: "+60" },
  { name: "Malawi", iso: "MW", dial: "+265" },
  { name: "Maldives", iso: "MV", dial: "+960" },
  { name: "Mali", iso: "ML", dial: "+223" },
  { name: "Malte", iso: "MT", dial: "+356" },
  { name: "Maroc", iso: "MA", dial: "+212" },
  { name: "Maurice", iso: "MU", dial: "+230" },
  { name: "Mauritanie", iso: "MR", dial: "+222" },
  { name: "Mexique", iso: "MX", dial: "+52" },
  { name: "Moldavie", iso: "MD", dial: "+373" },
  { name: "Monaco", iso: "MC", dial: "+377" },
  { name: "Mongolie", iso: "MN", dial: "+976" },
  { name: "Monténégro", iso: "ME", dial: "+382" },
  { name: "Mozambique", iso: "MZ", dial: "+258" },
  { name: "Namibie", iso: "NA", dial: "+264" },
  { name: "Népal", iso: "NP", dial: "+977" },
  { name: "Nicaragua", iso: "NI", dial: "+505" },
  { name: "Niger", iso: "NE", dial: "+227" },
  { name: "Nigeria", iso: "NG", dial: "+234" },
  { name: "Norvège", iso: "NO", dial: "+47" },
  { name: "Nouvelle-Zélande", iso: "NZ", dial: "+64" },
  { name: "Oman", iso: "OM", dial: "+968" },
  { name: "Ouganda", iso: "UG", dial: "+256" },
  { name: "Ouzbékistan", iso: "UZ", dial: "+998" },
  { name: "Pakistan", iso: "PK", dial: "+92" },
  { name: "Palestine", iso: "PS", dial: "+970" },
  { name: "Panama", iso: "PA", dial: "+507" },
  { name: "Papouasie-Nouvelle-Guinée", iso: "PG", dial: "+675" },
  { name: "Paraguay", iso: "PY", dial: "+595" },
  { name: "Pays-Bas", iso: "NL", dial: "+31" },
  { name: "Pérou", iso: "PE", dial: "+51" },
  { name: "Philippines", iso: "PH", dial: "+63" },
  { name: "Pologne", iso: "PL", dial: "+48" },
  { name: "Portugal", iso: "PT", dial: "+351" },
  { name: "Qatar", iso: "QA", dial: "+974" },
  { name: "République centrafricaine", iso: "CF", dial: "+236" },
  { name: "République dominicaine", iso: "DO", dial: "+1809" },
  { name: "République tchèque", iso: "CZ", dial: "+420" },
  { name: "Roumanie", iso: "RO", dial: "+40" },
  { name: "Royaume-Uni", iso: "GB", dial: "+44" },
  { name: "Russie", iso: "RU", dial: "+7" },
  { name: "Rwanda", iso: "RW", dial: "+250" },
  { name: "Saint-Marin", iso: "SM", dial: "+378" },
  { name: "Salvador", iso: "SV", dial: "+503" },
  { name: "Sénégal", iso: "SN", dial: "+221" },
  { name: "Serbie", iso: "RS", dial: "+381" },
  { name: "Seychelles", iso: "SC", dial: "+248" },
  { name: "Sierra Leone", iso: "SL", dial: "+232" },
  { name: "Singapour", iso: "SG", dial: "+65" },
  { name: "Slovaquie", iso: "SK", dial: "+421" },
  { name: "Slovénie", iso: "SI", dial: "+386" },
  { name: "Somalie", iso: "SO", dial: "+252" },
  { name: "Soudan", iso: "SD", dial: "+249" },
  { name: "Soudan du Sud", iso: "SS", dial: "+211" },
  { name: "Sri Lanka", iso: "LK", dial: "+94" },
  { name: "Suède", iso: "SE", dial: "+46" },
  { name: "Suisse", iso: "CH", dial: "+41" },
  { name: "Suriname", iso: "SR", dial: "+597" },
  { name: "Syrie", iso: "SY", dial: "+963" },
  { name: "Tadjikistan", iso: "TJ", dial: "+992" },
  { name: "Tanzanie", iso: "TZ", dial: "+255" },
  { name: "Tchad", iso: "TD", dial: "+235" },
  { name: "Thaïlande", iso: "TH", dial: "+66" },
  { name: "Timor oriental", iso: "TL", dial: "+670" },
  { name: "Togo", iso: "TG", dial: "+228" },
  { name: "Trinité-et-Tobago", iso: "TT", dial: "+1868" },
  { name: "Tunisie", iso: "TN", dial: "+216" },
  { name: "Turkménistan", iso: "TM", dial: "+993" },
  { name: "Turquie", iso: "TR", dial: "+90" },
  { name: "Ukraine", iso: "UA", dial: "+380" },
  { name: "Uruguay", iso: "UY", dial: "+598" },
  { name: "Vanuatu", iso: "VU", dial: "+678" },
  { name: "Vatican", iso: "VA", dial: "+39" },
  { name: "Venezuela", iso: "VE", dial: "+58" },
  { name: "Viêt Nam", iso: "VN", dial: "+84" },
  { name: "Yémen", iso: "YE", dial: "+967" },
  { name: "Zambie", iso: "ZM", dial: "+260" },
  { name: "Zimbabwe", iso: "ZW", dial: "+263" },
];

export const DEFAULT_COUNTRY = COUNTRIES.find((c) => c.iso === "GA")!;
export const ALL_COUNTRIES: Country = { name: "Tous les pays", iso: "ALL", dial: "" };

export function countryByName(name?: string | null) {
  if (!name) return DEFAULT_COUNTRY;
  return COUNTRIES.find((c) => c.name.toLowerCase() === name.toLowerCase()) || DEFAULT_COUNTRY;
}

export function countryByIso(iso?: string | null) {
  if (!iso) return DEFAULT_COUNTRY;
  return COUNTRIES.find((c) => c.iso === iso.toUpperCase()) || DEFAULT_COUNTRY;
}

export function formatPhone(raw: string, country: Country) {
  const trimmed = raw.trim();
  if (!trimmed) return "";
  if (trimmed.startsWith("+") || trimmed.startsWith("00")) return trimmed;
  const local = trimmed.replace(/^0+/, "").replace(/\s/g, "");
  return `${country.dial}${local}`;
}
